CREATE TABLE CASA_DE_APOSTA (
    ID_CASA_APOSTA  SMALLSERIAL PRIMARY KEY,
    NOME            VARCHAR(20) NOT NULL,
    CNPJ            CHAR(18) UNIQUE NOT NULL,
    DATA_CRIACAO    TIMESTAMP NOT NULL,
    ENDERECO        VARCHAR(100),
    TELEFONE        VARCHAR(15)
);

CREATE TABLE USUARIO (
    ID_USUARIO      SMALLSERIAL PRIMARY KEY,
    NOME            VARCHAR(15) NOT NULL,
    SOBRENOME       VARCHAR(30) NOT NULL,
    DATA_NASCIMENTO TIMESTAMP NOT NULL,
    ENDERECO        VARCHAR(100),
    TELEFONE        VARCHAR(15),
    SENHA           VARCHAR(88) NOT NULL,
    EMAIL           VARCHAR(50) NOT NULL,
    CPF             VARCHAR(11) UNIQUE NOT NULL,
    TIPO            SMALLINT NOT NULL
);

CREATE TABLE GERENCIA (
    ID_USUARIO_ADMINISTRADOR    SMALLINT,
    ID_CASA_APOSTA              SMALLINT,

    CONSTRAINT pk_gerencia PRIMARY KEY (ID_USUARIO_ADMINISTRADOR, ID_CASA_APOSTA),
    CONSTRAINT fk_gerencia_administrador FOREIGN KEY (ID_USUARIO_ADMINISTRADOR) REFERENCES USUARIO (ID_USUARIO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_gerencia_casa FOREIGN KEY (ID_CASA_APOSTA) REFERENCES CASA_DE_APOSTA (ID_CASA_APOSTA)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE CLIENTES (
    ID_CASA_APOSTA          SMALLINT,
    ID_USUARIO_APOSTADOR    SMALLINT,
    SALDO                   DECIMAL (10,2)  NOT NULL,

    CONSTRAINT pk_clientes PRIMARY KEY (ID_CASA_APOSTA, ID_USUARIO_APOSTADOR),
    CONSTRAINT fk_clientes_usuario FOREIGN KEY (ID_USUARIO_APOSTADOR) REFERENCES USUARIO (ID_USUARIO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_clientes_casa FOREIGN KEY (ID_CASA_APOSTA) REFERENCES CASA_DE_APOSTA (ID_CASA_APOSTA)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE BILHETE (
    ID_BILHETE              SMALLSERIAL PRIMARY KEY,
    DATA                    TIMESTAMP NOT NULL,
    STATUS                  SMALLINT NOT NULL DEFAULT 0,
    ID_USUARIO_APOSTADOR    SMALLINT NOT NULL,

    CONSTRAINT fk_bilhete_usuario FOREIGN KEY (ID_USUARIO_APOSTADOR) REFERENCES USUARIO (ID_USUARIO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE JOGO (
    ID_JOGO                 SMALLSERIAL PRIMARY KEY,
    TIME_CASA               VARCHAR(30) NOT NULL,
    TIME_FORA               VARCHAR(30) NOT NULL,
    DATA_INICIO             TIMESTAMP NOT NULL,
    DATA_FIM                TIMESTAMP NOT NULL
);

CREATE TABLE RESULTADO (
    ID_JOGO                 SMALLINT PRIMARY KEY,
    GOLS_TIME_CASA          SMALLINT NOT NULL,
    GOLS_TIME_FORA          SMALLINT NOT NULL,
    TOTAL_ESCANTEIOS        SMALLINT NOT NULL,

    CONSTRAINT fk_resultado_jogo FOREIGN KEY (ID_JOGO) REFERENCES JOGO (ID_JOGO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE APOSTA (
    ID_APOSTA               SERIAL PRIMARY KEY,
    ODD                     DECIMAL (4,2) NOT NULL,
    TIPO                    SMALLINT NOT NULL,
    ID_JOGO                 SMALLINT NOT NULL,
    ID_CASA_APOSTA          SMALLINT NOT NULL,

    CONSTRAINT fk_aposta_jogo FOREIGN KEY (ID_JOGO) REFERENCES JOGO (ID_JOGO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_aposta_casa FOREIGN KEY (ID_CASA_APOSTA) REFERENCES CASA_DE_APOSTA (ID_CASA_APOSTA)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE RESULTADO_FINAL (
    ID_APOSTA               SMALLINT PRIMARY KEY,
    RESULTADO_FINAL         CHAR(4) NOT NULL,
    
    CONSTRAINT fk_resultado_final_aposta FOREIGN KEY (ID_APOSTA) REFERENCES APOSTA(ID_APOSTA)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE NUMERO_ESCANTEIOS (
    ID_APOSTA               SMALLINT PRIMARY KEY,
    TIPO                    SMALLINT NOT NULL,
    NUMERO                  SMALLINT NOT NULL,

    CONSTRAINT fk_numero_escanteios_aposta FOREIGN KEY (ID_APOSTA) REFERENCES APOSTA (ID_APOSTA)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE NUMERO_GOLS (
    ID_APOSTA               SMALLINT PRIMARY KEY,
    TIPO                    SMALLINT NOT NULL,
    NUMERO                  SMALLINT NOT NULL,

    CONSTRAINT fk_numero_gols_aposta FOREIGN KEY (ID_APOSTA) REFERENCES APOSTA (ID_APOSTA)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE BILHETE_TEM_APOSTA (
    ID_BILHETE              SMALLINT,
    ID_APOSTA               SMALLINT,
    ODD                     DECIMAL (4,2) NOT NULL,
    VALOR_APOSTADO          DECIMAL (10,2) NOT NULL,
    STATUS                  SMALLINT NOT NULL DEFAULT 0,
    RESULTADO               SMALLINT,

    CONSTRAINT pk_bilhete_tem_aposta PRIMARY KEY (ID_BILHETE, ID_APOSTA),
    CONSTRAINT fk_bilhete_tem_aposta_bilhete FOREIGN KEY (ID_BILHETE) REFERENCES BILHETE (ID_BILHETE)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_bilhete_tem_aposta_aposta FOREIGN KEY (ID_APOSTA) REFERENCES APOSTA (ID_APOSTA)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

