CREATE SCHEMA CASA_APOSTAS;

CREATE TABLE CASA_DE_APOSTA (
    ID_CASA_APOSTA  INTEGER PRIMARY KEY,
    NOME            VARCHAR(20),
    CNPJ            CHAR(18),
    DATA_CRIACAO    TIMESTAMP,
    ENDERECO        VARCHAR(100),
    TELEFONE        VARCHAR(15)
);

CREATE TABLE USUARIO (
    ID_USUARIO      SMALLINT PRIMARY KEY,
    NOME            VARCHAR(15),
    SOBRENOME       VARCHAR(15),
    DATA_NASCIMENTO TIMESTAMP,
    ENDERECO        VARCHAR(100),
    TELEFONE        VARCHAR(15),
    SENHA           VARCHAR(88),
    EMAIL           VARCHAR(50),
    CPF             VARCHAR(11),
    TIPO            SMALLINT,
)